export const DEVTOOLS_EVENTS = {
  TIME_TRAVEL: 'SYNAPSE_DEVTOOLS_TIME_TRAVEL',
  RESET: 'SYNAPSE_DEVTOOLS_RESET',
  UPDATE: 'SYNAPSE_DEVTOOLS_UPDATE',
} as const;

export const DEVTOOLS_DEFAULTS = {
  MAX_HISTORY: 100,
  CLEANUP_DELAY: 100,
  DEFAULT_ACTION: 'SET',
} as const;

