export const REDUX_DEVTOOLS_EXTENSION_KEY = '__REDUX_DEVTOOLS_EXTENSION__';

export const REDUX_DEVTOOLS_DEFAULTS = {
  NAME: 'Synapse',
  ACTION_TYPE: 'SET',
  INIT_DELAY_MS: 0,
} as const;

export const REDUX_DEVTOOLS_MESSAGES = {
  DISPATCH: 'DISPATCH',
  JUMP_TO_ACTION: 'JUMP_TO_ACTION',
  JUMP_TO_STATE: 'JUMP_TO_STATE',
} as const;
